name: g4mp2_ip
channels:
  - conda-forge
  - openbabel
  - matsci
  - pytorch
  - rdkit
dependencies:
  - libgfortran
  - python==3.7.2
  - numpy==1.15.4
  - pymatgen==2020.4.29
  - pandas==0.23.4
  - scikit-learn==0.20.0
  - pytorch==1.1.*
  - matplotlib==3.0.3
  - openbabel==2.4.1
  - tensorflow==1.13.1
  - rdkit==2019.03.2.0
  - xlrd==1.2.0
  - jupyterlab
  - pytest
  - pip
  - pip:
    - mdf_forge
    - dlhub_sdk
    - schnetpack==0.3.*
    - git+https://github.com/WardLT/qml.git@change_xyz#egg=qml
    - -e .
